#!/bin/sh
set -e

USER=iotedge
GROUP=iotedge

#if ! getent passwd ${USER} >/dev/null; then
#adduser --system ${USER} --home /var/lib/iotedge --shell /bin/false
#fi

#if ! getent group ${GROUP} >/dev/null; then
#addgroup --system ${GROUP}
#fi

# add iotedge user to docker group so that it can talk to the docker socket
#if getent group docker >/dev/null; then
#adduser ${USER} docker
#fi

# Add each admin user to the iotedge group - for systems installed before precise
#for u in $(getent group admin | sed -e "s/^.*://" -e "s/,/ /g"); do
#adduser "$u" ${USER} >/dev/null || true
#done

# Add each sudo user to the iotedge group
#for u in $(getent group sudo | sed -e "s/^.*://" -e "s/,/ /g"); do
#adduser "$u" ${USER} >/dev/null || true
#done


#if id -u $USER > /dev/null 2>&1; then
#    chown ${USER}:${GROUP} /var/lib/iotedge
#    chown ${USER}:${GROUP} /var/log/iotedge
#    chown ${USER}:${GROUP} /etc/iotedge/config.yaml

#    chmod 755 /var/lib/iotedge
#    chmod 755 /var/log/iotedge
#    chmod 400 /etc/iotedge/config.yaml

#fi

# copy the default config file to the snap directory
cp /$SNAP/etc/iotedge/config.yaml /$SNAP_DATA/config.yaml

# set the  IOTEDGE_HOMEDIR environment variable
mkdir $SNAP_DATA/iotedge
export IOTEDGE_HOMEDIR=$SNAP_DATA/iotedge

# Set the hostname
#sed -i "s/hostname: \"<ADD HOSTNAME HERE>\"/hostname: \"$(hostname)\"/g" /$SNAP/etc/iotedge/config.yaml
sed -i "s/hostname: \"<ADD HOSTNAME HERE>\"/hostname: \"$(hostname)\"/g" /$SNAP_DATA/config.yaml

echo "==============================================================================="
echo ""
echo "                              Azure IoT Edge"
echo ""
echo "  IMPORTANT: Please update the configuration file located at:"
echo ""
echo "    /etc/iotedge/config.yaml"
echo ""
echo "  with your device's provisioning information. You will need to restart the"
echo "  'iotedge' service for these changes to take effect."
echo ""
echo "  To restart the 'iotedge' service, use:"
echo ""
echo "    'systemctl restart iotedge'"
echo ""
echo "    - OR -"
echo ""
echo "    /etc/init.d/iotedge restart"
echo ""
echo "  These commands may need to be run with sudo depending on your environment."
echo ""
echo "==============================================================================="


