#!/bin/sh
set -e

USER=iotedge
GROUP=iotedge

# copy the default config file to the snap directory
cp /$SNAP/etc/iotedge/config.yaml /$SNAP_COMMON/config.yaml

# set the  IOTEDGE_HOMEDIR
mkdir $SNAP_COMMON/iotedge
sed -i "s#homedir: \"/var/lib/iotedge\"#homedir: \"${SNAP_COMMON}/iotedge\"#g" $SNAP_COMMON/config.yaml

# Set the hostname
sed -i "s#hostname: \"<ADD HOSTNAME HERE>\"#hostname: \"$(hostname)\"#g" /$SNAP_COMMON/config.yaml

echo "==============================================================================="
echo ""
echo "                              Azure IoT Edge"
echo ""
echo "  IMPORTANT: Please update the configuration file located at:"
echo ""
echo "    /etc/iotedge/config.yaml"
echo ""
echo "  with your device's provisioning information. You will need to restart the"
echo "  'iotedge' service for these changes to take effect."
echo ""
echo "  To restart the 'iotedge' service, use:"
echo ""
echo "    'systemctl restart iotedge'"
echo ""
echo "    - OR -"
echo ""
echo "    /etc/init.d/iotedge restart"
echo ""
echo "  These commands may need to be run with sudo depending on your environment."
echo ""
echo "==============================================================================="